GET http://localhost:8080/planet
Accept: application/json

###


GET http://localhost:8080/planet/G
Accept: application/json

###

GET http://localhost:8080/planetroute
Accept: application/json

###

GET http://localhost:8080/shortestpath?source=A&destination=K'&includeTraffic=false
Accept: application/json

###
